version: '3.8'

services:
  app-pichichi:
    build: .
    image: pichichi:v1
    container_name: contenedor-pichichi
    stdin_open: true
    tty: true
    networks:
      - red-jenkins

  jenkins:
    image: jenkins/jenkins:lts
    container_name: mi_jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - red-jenkins
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:community
    container_name: mi_sonar
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:h2:tcp://localhost/sonar;START_DELAY_SECS=0
    networks:
      - red-jenkins

volumes:
  jenkins_home:

networks:
  red-jenkins:
